#!/bin/sh
#
###################################################
# Kibojoe Linux 			          #
# Updated 24.06.2017 15:02:02 		          #
# Version 0.1-1 			          #
# Name upnotifier ; Update Notifier               #
# Use chmod +x upnotifier ; /usr/bin/             #
# Credits Chrysostomus (Manjaro Linux)		  #
# Site http://polr.me/1gmk                        #
# Adapted Holmes (Manjaro Brasil)                 #
# License Copyleft                                #
###################################################

trap 'rm /tmp/{pacmanupdates,aurupdates} 2>/dev/null' INT TERM QUIT EXIT
nb_pac=$(checkupdates | tee /tmp/pacmanupdates | wc -l)
if [ -f /usr/bin/yaourt ]; then
   nb_aur=$(yaourt -Qua | grep "^aur/" | tee /tmp/aurupdates | wc -l)
else
   nb_aur=0
fi

if ((nb_pac>0 || nb_aur>0)); then
  ((nb_aur>0)) && nb_aur="+ ${nb_aur}"
  ((nb_aur==0)) && unset nb_aur
  notify-send "Hello, ${nb_pac} ${nb_aur} updates for Kibojoe Linux!"
fi
